# Generated by Django 5.2.1 on 2025-05-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='image'),
        ),
    ]
