# Generated by Django 5.2.1 on 2025-05-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_alter_register_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prodect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_brand', models.CharField()),
                ('product_image', models.FileField(blank=True, null=True, upload_to='image')),
                ('product_price', models.IntegerField()),
                ('product_discound', models.IntegerField()),
                ('product_description', models.CharField()),
                ('product_stock', models.IntegerField()),
                ('product_IsAvailable', models.BooleanField(default=True)),
                ('product_createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
